import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#111412",
        "on-secondary-fixed-variant": "#3c475d",
        "tertiary-container": "#001b33",
        "secondary-fixed-dim": "#bbc6e2",
        "on-primary-container": "#768497",
        "on-secondary": "#263046",
        primary: "#bac8dc",
        "on-tertiary-fixed-variant": "#2f4865",
        "primary-fixed-dim": "#bac8dc",
        "error-container": "#93000a",
        "on-primary-fixed": "#0f1c2c",
        background: "#111412",
        "surface-bright": "#373a37",
        "on-background": "#e2e3df",
        "inverse-on-surface": "#2f312e",
        "on-error": "#690005",
        "surface-variant": "#333533",
        "tertiary-fixed-dim": "#afc9ea",
        "primary-container": "#0d1b2a",
        "on-secondary-fixed": "#101b30",
        error: "#ffb4ab",
        "surface-container-low": "#1a1c1a",
        "on-surface": "#e2e3df",
        outline: "#8e9196",
        "surface-tint": "#bac8dc",
        "surface-container-lowest": "#0c0f0d",
        "on-tertiary-container": "#6b85a4",
        "tertiary-fixed": "#d1e4ff",
        "on-primary-fixed-variant": "#3a4859",
        surface: "#111412",
        "primary-fixed": "#d6e4f9",
        "outline-variant": "#44474c",
        "surface-container-high": "#282b28",
        "inverse-surface": "#e2e3df",
        "secondary-container": "#3e4960",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#c4c6cc",
        "secondary-fixed": "#d7e2ff",
        "on-tertiary": "#17324d",
        "surface-container-highest": "#333533",
        "surface-container": "#1e201e",
        "inverse-primary": "#525f71",
        "on-primary": "#243141",
        secondary: "#bbc6e2",
        "on-secondary-container": "#adb8d3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "16px",
        unit: "8px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "display-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "rating-number": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "rating-number": ["28px", { lineHeight: "1", fontWeight: "700" }],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],

  safelist: [
    "bg-red-500",
    "bg-blue-500",
    "bg-green-500",
    "rounded-tr-lg",
    "rounded-br-lg",
    "rounded-tl-lg",
    "rounded-bl-lg",
  ],
};
export default config;
